# Generated by Django 5.2.7 on 2025-10-03 00:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('style', models.CharField(choices=[('satellite', 'Satellite'), ('street', 'Street'), ('3d', '3D'), ('gps', 'GPS')], default='street', max_length=20, verbose_name='Style')),
                ('public_view', models.BooleanField(default=False, verbose_name='Public View')),
                ('public_contribution', models.BooleanField(default=False, verbose_name='Public Contribution')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_maps', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Map',
                'verbose_name_plural': 'Maps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MapCollaborator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='maps.map', verbose_name='Map')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborated_maps', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Map Collaborator',
                'verbose_name_plural': 'Map Collaborators',
                'ordering': ['-created_at'],
                'unique_together': {('map', 'user')},
            },
        ),
        migrations.CreateModel(
            name='MapPin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude coordinate (-90 to 90)', max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude coordinate (-180 to 180)', max_digits=9, verbose_name='Longitude')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('content_url', models.URLField(max_length=500, verbose_name='Content URL')),
                ('content_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('text', 'Text'), ('audio', 'Audio')], default='image', max_length=20, verbose_name='Content Type')),
                ('icon', models.CharField(choices=[('point', 'Point'), ('camera', 'Camera'), ('mic', 'Microphone'), ('photo', 'Photo'), ('text', 'Text'), ('video', 'Video'), ('audio', 'Audio'), ('location', 'Location'), ('marker', 'Marker')], default='point', max_length=20, verbose_name='Icon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='maps.map', verbose_name='Map')),
                ('placed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placed_pins', to=settings.AUTH_USER_MODEL, verbose_name='Placed By')),
            ],
            options={
                'verbose_name': 'Map Pin',
                'verbose_name_plural': 'Map Pins',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['map', 'timestamp'], name='maps_mappin_map_id_652d50_idx'), models.Index(fields=['latitude', 'longitude'], name='maps_mappin_latitud_79e0b8_idx')],
            },
        ),
    ]
